/* =====================================================================
   words.js — your vocabulary bank for Nuklearny Polski
   ---------------------------------------------------------------------
   THIS FILE IS YOURS TO EDIT. The app code lives in index.html and never
   needs to change when you add words here. Just keep both files together
   and upload both when you publish.

   Format:  ["polish", "english", "tag1", "tag2", ...]
            - "polish"/"english": base/dictionary forms, lowercase.
            - Tags are OPTIONAL. Add none, one, or as many as you like.
              A tag is just a lowercase label (e.g. "weather", "calendar")
              that groups words together.
   Example: ["deszcz", "rain", "weather"]
            ["poniedziałek", "Monday",                "calendar", "days"]
            ["kot", "cat"]            <- perfectly fine with no tags

   What tags unlock (handled automatically by index.html):
     • In the Word list, search a tag name to see every word carrying it,
       and click a tag chip to filter the table.
     • In Flashcards, pick one or more tags to study just those words —
       e.g. select "calendar" + "weather" to drill both at once.

   Sorted A->Z by the Polish word, with // -- X -- letter dividers.
   To add a word: find its letter, drop in a new line in order, save.
   ===================================================================== */

const COMMON_WORDS = [
  // — A —
  ["a",                      "and / but"],
  ["aby",                    "in order to / so that"],
  ["albo",                   "or"],
  ["ale",                    "but"],
  ["ani",                    "nor"],
  ["apteka",                 "pharmacy"],
  ["auto",                   "car, automobile"],
  ["autobus",                "bus"],
  ["aż",                     "until / up to / as many as"],

  // — B —
  ["babcia",                 "grandmother",           "family"],
  ["bać się",                "to be afraid"],
  ["bank",                   "bank"],
  ["bardzo",                 "very"],
  ["bez",                    "without"],
  ["biały",                  "white"],
  ["biblioteka",             "library"],
  ["biedny",                 "poor"],
  ["biegać",                 "to run"],
  ["bilet",                  "ticket"],
  ["biuro",                  "office",                 "nuclear"],
  ["blisko",                 "near"],
  ["bo",                     "because"],
  ["bogaty",                 "rich"],
  ["ból",                    "pain"],
  ["brać",                   "to take"],
  ["brat",                   "brother"],
  ["brązowy",                "brown"],
  ["brudny",                 "dirty"],
  ["brzuch",                 "stomach / belly"],
  ["brzydki",                "ugly"],
  ["budować",                "to build",              "nuclear"],
  ["burza",                  "storm",                 "weather"],
  ["buty",                   "shoes"],
  ["być",                    "to be"],

  // — C —
  ["cały",                   "whole"],
  ["cel",                    "goal / aim"],
  ["cena",                   "price"],
  ["chcieć",                 "to want"],
  ["chleb",                  "bread"],
  ["chłodny",                "cool"],
  ["chłopiec",               "boy"],
  ["chmura",                 "cloud",                 "weather"],
  ["chociaż",                "although"],
  ["choć",                   "although"],
  ["chodzić",                "to walk / go"],
  ["choroba",                "illness"],
  ["chory",                  "sick"],
  ["chwila",                 "moment"],
  ["ciało",                  "body"],
  ["cichy",                  "quiet"],
  ["ciekawy",                "interesting"],
  ["ciemny",                 "dark"],
  ["cienki",                 "thin"],
  ["ciepły",                 "warm",                  "weather"],
  ["cieszyć się",            "to be glad"],
  ["ciężki",                 "heavy / hard"],
  ["ciocia",                 "aunt",                  "family"],
  ["ciśnienie",              "pressure",              "nuclear","weather"]
  ["co",                     "what"],
  ["coś",                    "something"],
  ["córka",                  "daughter",              "family"],
  ["cukier",                 "sugar"],
  ["ćwierćfinał",            "quarterfinal",          "sports"],
  ["czapka",                 "cap"],
  ["czarny",                 "black"],
  ["czas",                   "time"],
  ["czasem",                 "sometimes"],
  ["czekać",                 "to wait"],
  ["czemu",                  "why / what for"],
  ["czerwiec",               "June",                  "calendar"],
  ["czerwony",               "red"],
  ["często",                 "often"],
  ["część",                  "part"],
  ["człowiek",               "person / human"],
  ["czterdzieści",           "forty"],
  ["czternaście",            "fourteen"],
  ["czuć",                   "to feel"],
  ["czwartek",               "Thursday",              "calendar"],
  ["czy",                    "whether"],
  ["czyj",                   "whose"],
  ["czysty",                 "clean"],
  ["czytać",                 "to read"],

  // — D —
  ["dać",                    "to give"],
  ["daleko",                 "far"],
  ["data",                   "date",                  "calendar"],
  ["dawać",                  "to give"],
  ["decydować",              "to decide"],
  ["deszcz",                 "rain",                  "weather"],
  ["dla",                    "for"],
  ["dlaczego",               "why"],
  ["długi",                  "long"],
  ["długopis",               "pen"],
  ["długość",                "length"],
  ["dnia",                   "on"],
  ["do",                     "to / into"],
  ["do ustalenia",           "to be determined",      "sports"],
  ["dobry",                  "good"],
  ["dokąd",                  "where to"],
  ["dolny",                  "lower"],
  ["dom",                    "house / home"],
  ["dostać",                 "to get / receive"],
  ["dość",                   "enough / quite"],
  ["drewno",                 "wood"],
  ["droga",                  "road / way"],
  ["drogi",                  "expensive / dear"],
  ["drugi",                  "second"],
  ["drzewo",                 "tree"],
  ["drzwi",                  "door"],
  ["duży",                   "big"],
  ["dwadzieścia",            "twenty"],
  ["dwanaście",              "twelve"],
  ["dworzec",                "station (rail/bus)"],
  ["dyrektor",               "director",              "nuclear"],
  ["dziadek",                "grandfather"],
  ["działać",                "to work / operate"],
  ["dzieci",                 "children"],
  ["dziecko",                "child"],
  ["dzień",                  "day",                   "calendar"],
  ["dziewczyna",             "girl"],
  ["dziewięćdziesiąt",       "ninety"],
  ["dziewiętnaście",         "nineteen"],
  ["dziękować",              "to thank"],
  ["dziś",                   "today",                 "calendar"],
  ["dzwonić",                "to call / ring"],

  // — E —
  ["edukacja",               "education"],
  ["ekspert",                "expert"],
  ["elektrownia",            "power plant",           "nuclear"],
  ["energia",                "energy",                "nuclear"],

  // — F —
  ["filiżanka",              "cup"],
  ["film",                   "film"],
  ["fioletowy",              "purple"],
  ["firma",                  "company",               "nuclear"],

  // — G —
  ["gazeta",                 "newspaper"],
  ["gdy",                    "when"],
  ["gdzie",                  "where"],
  ["głośny",                 "loud"],
  ["głowa",                  "head"],
  ["główny",                 "main"],
  ["godzinowa",              "hourly",                "calendar"],
  ["gorący",                 "hot",                   "weather"],
  ["gorzki",                 "bitter"],
  ["gospodarka",             "economy"],
  ["gość",                   "guest"],
  ["gotować",                "to cook"],
  ["gotowy",                 "ready"],
  ["góra",                   "mountain"],
  ["górny",                  "upper"],
  ["grać",                   "to play"],
  ["granica",                "border"],
  ["gruby",                  "thick / fat"],
  ["grudzień",               "December",              "calendar"],
  ["gwiazda",                "star"],

  // — H —
  ["historia",               "history / story"],
  ["hotel",                  "hotel"],

  // — I —
  ["i",                      "and"],
  ["ich",                    "their"],
  ["ile",                    "how much / how many"],
  ["ilość",                  "quantity"],
  ["inny",                   "other"],
  ["inżynier",               "engineer",               "nuclear"],
  ["iść",                    "to go (on foot)"],

  // — J —
  ["ja",                     "I"],
  ["jądrowy",                "nuclear",                "nuclear"],
  ["jakość",                 "quality",                "weather"],
  ["jabłko",                 "apple"],
  ["jajko",                  "egg"],
  ["jak",                    "how"],
  ["jaki",                   "what kind of"],
  ["jako",                   "as"],
  ["jakość",                 "quality"],
  ["jasny",                  "bright / light"],
  ["jechać",                 "to go (by vehicle)"],
  ["jedenaście",             "eleven"],
  ["jego",                   "his"],
  ["jej",                    "her"],
  ["jesień",                 "autumn",                 "calendar"],
  ["jeszcze",                "still / yet"],
  ["jeść",                   "to eat"],
  ["jeśli",                  "if"],
  ["jezioro",                "lake"],
  ["jeździć",                "to travel / drive"],
  ["jeżeli",                 "if"],
  ["język",                  "language / tongue"],
  ["jutro",                 "tomorrow",                "calendar"],
  ["już",                    "already"],

  // — K —
  ["kalendarz",              "calendar",               "calendar"],
  ["kamień",                 "stone"],
  ["karta",                  "card"],
  ["kawiarnia",              "café"],
  ["każdy",                  "each / every"],
  ["kiedy",                  "when"],
  ["kierowca",               "driver"],
  ["kierunek",               "direction",              "weather"],
  ["kierownik",              "manager",                "nuclear"],
  ["kino",                   "cinema"],
  ["klient",                 "customer"],
  ["klucz",                  "key"],
  ["kłamstwo",               "lie"],
  ["kobieta",                "woman"],
  ["kochać",                 "to love"],
  ["kolacja",                "supper"],
  ["kolega",                 "colleague / friend (m)"],
  ["koleżanka",              "friend (f)"],
  ["kolor",                  "color"],
  ["komputer",               "computer",               "nuclear"],
  ["koniec",                 "end"],
  ["kontrolować",            "to control",             "nuclear"],
  ["koń",                    "horse"],
  ["kończyć",                "to finish"],
  ["koniec",                 "finish",                 "sports"],
  ["koszt",                  "cost"],
  ["koszula",                "shirt"],
  ["kościół",                "church"],
  ["kość",                   "bone"],
  ["kot",                    "cat"],
  ["kraj",                   "country"],
  ["krew",                   "blood"],
  ["krowa",                  "cow"],
  ["król",                   "king"],
  ["krótki",                 "short"],
  ["krzesło",                "chair"],
  ["książka",                "book"],
  ["księżyc",                "moon"],
  ["kto",                    "who"],
  ["ktoś",                   "someone"],
  ["który",                  "which"],
  ["kuchnia",                "kitchen"],
  ["kultura",                "culture"],
  ["kupić",                  "to buy (completed)"],
  ["kupować",                "to buy"],
  ["kurtka",                 "jacket"],
  ["kwaśny",                 "sour"],
  ["kwiat",                  "flower"],
  ["kwiecień",               "April",                 "calendar"],

  // — L —
  ["lampa",                  "lamp"],
  ["las",                    "forest"],
  ["latać",                  "to fly"],
  ["lato",                   "summer",                "calendar"],
  ["lekarz",                 "doctor"],
  ["lekki",                  "light"],
  ["lew",                    "lion"],
  ["lewy",                   "left (side)"],
  ["leżeć",                  "to lie down"],
  ["liczba",                 "number"],
  ["liczyć",                 "to count"],
  ["lipiec",                 "July",                  "calendar"],
  ["list",                   "letter"],
  ["listopad",               "November",              "calendar"],
  ["liść",                   "leaf"],
  ["litera",                 "letter (character)"],
  ["lotnisko",               "airport"],
  ["lód",                    "ice",                   "nuclear"],
  ["lub",                    "or"],
  ["lubić",                  "to like"],
  ["ludzie",                 "people"],
  ["luty",                   "February",              "calendar"],

  // — Ł —
  ["ładny",                  "pretty"],
  ["łatwy",                  "easy"],
  ["łazienka",               "bathroom"],
  ["łóżko",                  "bed"],
  ["łyżka",                  "spoon"],

  // — M —
  ["maj",                    "May",                   "calendar"],
  ["mały",                   "small"],
  ["mama",                   "mom"],
  ["martwić się",            "to worry"],
  ["marzec",                 "March",                 "calendar"],
  ["matka",                  "mother",                "family"],
  ["mąż",                    "husband",               "family"],
  ["metal",                  "metal"],
  ["mężczyzna",              "man"],
  ["mgła",                   "fog",                   "weather"],
  ["miasto",                 "city / town"],
  ["mieć",                   "to have"],
  ["miejsce",                "place"],
  ["mierzyć",                "to measure"],
  ["miesiąc",                "month",                 "calendar"],
  ["mieszkanie",             "apartment"],
  ["między",                 "between"],
  ["miękki",                 "soft"],
  ["mięso",                  "meat"],
  ["milion",                 "million"],
  ["miłość",                 "love"],
  ["miły",                   "nice / kind"],
  ["mimo",                   "despite"],
  ["mistrzostwa",            "championships",         "sports"],
  ["mleko",                  "milk"],
  ["młody",                  "young"],
  ["moc",                    "power"],
  ["mocny",                  "strong"],
  ["mokry",                  "wet"],
  ["morze",                  "sea"],
  ["most",                   "bridge"],
  ["może",                   "maybe"],
  ["możliwy",                "possible"],
  ["móc",                    "to be able / can"],
  ["mój",                    "my"],
  ["mówić",                  "to speak / say"],
  ["mózg",                   "brain"],
  ["musieć",                 "to have to / must"],
  ["muzeum",                 "museum"],
  ["muzyka",                 "music"],
  ["my",                     "we"],
  ["myć",                    "to wash"],
  ["mysz",                   "mouse"],
  ["myśl",                   "thought"],
  ["myśleć",                 "to think"],

  // — N —
  ["na",                     "on"],
  ["nad",                    "above / over"],
  ["nadzieja",               "hope"],
  ["nadchodzące",            "upcoming",               "sports"],
  ["najpierw",               "first / at first"],
  ["napisać",                "to write (completed)"],
  ["naprawiać",              "to repair"],
  ["następny",               "next"],
  ["nasz",                   "our"],
  ["naturalny",              "natural"],
  ["nauczyciel",             "teacher"],
  ["nauka",                  "science / learning"],
  ["naukowiec",              "scientist"],
  ["nawet",                  "even"],
  ["nic",                    "nothing"],
  ["niebieski",              "blue"],
  ["niebo",                  "sky / heaven",          "weather"],
  ["niedziela",              "Sunday",                "calendar"],
  ["niedźwiedź",             "bear"],
  ["nieść",                  "to carry"],
  ["nigdy",                  "never"],
  ["nikt",                   "nobody"],
  ["niski",                  "low / short",           "weather"],
  ["niż",                    "than"],
  ["noc",                    "night"],
  ["noga",                   "leg / foot"],
  ["nos",                    "nose"],
  ["nosić",                  "to carry / wear"],
  ["nowy",                   "new"],
  ["nóż",                    "knife"],
  ["nudny",                  "boring"],
  ["numer",                  "number (id)"],

  // — O —
  ["o",                      "about"],
  ["obiad",                  "lunch / dinner"],
  ["obok",                   "beside"],
  ["obraz",                  "picture / painting"],
  ["od",                     "from"],
  ["odczuwalna",             "perceptible/perceived", "weather"],
  ["odpoczywać",             "to rest"],
  ["odpowiadać",             "to answer"],
  ["odpowiedź",              "answer"],
  ["ogień",                  "fire"],
  ["ogród",                  "garden"],
  ["ojciec",                 "father"],
  ["okno",                   "window"],
  ["oko",                    "eye"],
  ["okolica",                "area / surroundings"],
  ["około",                  "around / about"],
  ["ołówek",                 "pencil"],
  ["on",                     "he"],
  ["ona",                    "she"],
  ["one",                    "they (non-male)"],
  ["oni",                    "they (men/mixed)"],
  ["ono",                    "it"],
  ["opady",                  "precipitation",         "weather"],
  ["opcje",                  "options"],
  ["oprócz",                 "besides / except"],
  ["oraz",                   "as well as"],
  ["osiemdziesiąt",          "eighty"],
  ["osiemnaście",            "eighteen"],
  ["osobno",                 "separately"],
  ["ostatni",                "last"],
  ["ostry",                  "sharp"],
  ["oświetlenie",            "lightning",             "weather"],
  ["otwarty",                "open"],
  ["otwierać",               "to open"],
  ["owca",                   "sheep"],
  ["owoc",                   "fruit"],

  // — P —
  ["palec",                  "finger"],
  ["pamiętać",               "to remember"],
  ["państwo",                "state / country"],
  ["papier",                 "paper"],
  ["para",                   "pair"],
  ["park",                   "park"],
  ["patrzeć",                "to look"],
  ["październik",            "October",               "calendar"],
  ["pełnia księżyca",        "full moon",             "weather"],
  ["pełny",                  "full"],
  ["pewny",                  "sure / certain"],
  ["piątek",                 "Friday",                "calendar"],
  ["pić",                    "to drink"],
  ["pielęgniarka",           "nurse"],
  ["pieniądze",              "money"],
  ["pierwszy",               "first"],
  ["pies",                   "dog"],
  ["pięćdziesiąt",           "fifty"],
  ["piękny",                 "beautiful"],
  ["piętnaście",             "fifteen"],
  ["piosenka",               "song"],
  ["pisać",                  "to write"],
  ["piwo",                   "beer"],
  ["plac",                   "square"],
  ["plecy",                  "back"],
  ["płacić",                 "to pay"],
  ["płakać",                 "to cry"],
  ["płaszcz",                "coat"],
  ["pływać",                 "to swim"],
  ["po",                     "after"],
  ["pochmurnie",             "cloudy",                "weather"],
  ["pociąg",                 "train"],
  ["początek",               "beginning"],
  ["poczta",                 "post office"],
  ["pod",                    "under"],
  ["podczas",                "during"],
  ["podobny",                "similar"],
  ["pogoda",                 "weather",               "weather"],
  ["podsumowanie",           "summary"],
  ["pokazać",                "to show"],
  ["pokój",                  "room / peace"],
  ["pole",                   "field"],
  ["policjant",              "police officer"],
  ["polityka",               "politics"],
  ["połowa",                 "half"],
  ["południe",               "noon / south"],
  ["pomagać",                "to help"],
  ["pomarańczowy",           "orange"],
  ["pomóc",                  "to help (completed)"],
  ["pomysł",                 "idea"],
  ["poniedziałek",           "Monday",                "calendar"],
  ["ponieważ",               "because"],
  ["popołudnie",             "afternoon"],
  ["poprzedni",              "previous"],
  ["porywy",                 "gusts",                 "weather"],
  ["potem",                  "then / afterwards"],
  ["potrzebować",            "to need"],
  ["powiedzieć",             "to say (completed)"],
  ["powietrze",              "air",                   "weather"],
  ["powód",                  "reason"],
  ["pójść",                  "to go (completed)"],
  ["praca",                  "work / job"],
  ["pracować",               "to work"],
  ["pracownik",              "worker / employee"],
  ["prawda",                 "truth"],
  ["prawdziwy",              "real / true"],
  ["prawo",                  "law / right"],
  ["prawy",                  "right (side)"],
  ["prezent",                "gift"],
  ["prezydent",              "president"],
  ["problem",                "problem"],
  ["prosić",                 "to request"],
  ["prosty",                 "simple / straight"],
  ["prowadzić",              "to lead / drive"],
  ["próbować",               "to try"],
  ["prywatny",               "private"],
  ["przed",                  "before / in front of"],
  ["przemysł",               "industry"],
  ["przez",                  "through / by"],
  ["przy",                   "next to"],
  ["przyjaciel",             "friend"],
  ["przyjaźń",               "friendship"],
  ["przyjść",                "to come"],
  ["przykład",               "example"],
  ["przystanek",             "(bus/tram) stop"],
  ["ptak",                   "bird"],
  ["publiczny",              "public"],
  ["pusty",                  "empty"],
  ["pytać",                  "to ask"],
  ["pytanie",                "question"],

  // — R —
  ["rano",                   "morning"],
  ["raz",                    "once / one time"],
  ["razem",                  "together"],
  ["region",                 "region"],
  ["religia",                "religion"],
  ["restauracja",            "restaurant"],
  ["reaktor",                "reactor",               "nuclear"],
  ["ręka",                   "hand / arm"],
  ["robić",                  "to do / make"],
  ["rodzina",                "family",                "family"],
  ["rok",                    "year",                  "calendar"],
  ["roślina",                "plant"],
  ["rower",                  "bicycle"],
  ["rozmawiać",              "to talk"],
  ["rozumieć",               "to understand"],
  ["równy",                  "equal"],
  ["różny",                  "different"],
  ["różowy",                 "pink"],
  ["ryba",                   "fish"],
  ["rynek",                  "market square"],
  ["rzadko",                 "rarely"],
  ["rząd",                   "government"],
  ["rzecz",                  "thing"],
  ["rzeczywista",            "actual"],
  ["rzeka",                  "river"],

  // — S —
  ["sam",                    "alone / oneself"],
  ["samochód",               "car"],
  ["samolot",                "airplane"],
  ["sąsiad",                 "neighbor"],
  ["sekunda",                "second"],
  ["ser",                    "cheese"],
  ["serce",                  "heart"],
  ["siebie",                 "oneself"],
  ["siedemdziesiąt",         "seventy"],
  ["siedemnaście",           "seventeen"],
  ["siedzieć",               "to sit"],
  ["sierpień",               "August",                "calendar"],
  ["siła",                   "strength / force"],
  ["siostra",                "sister"],
  ["skąd",                   "where from"],
  ["sklep",                  "shop"],
  ["skończyć",               "to finish (completed)"],
  ["skóra",                  "skin"],
  ["słaby",                  "weak"],
  ["słodki",                 "sweet"],
  ["słony",                  "salty"],
  ["słoń",                   "elephant"],
  ["słońce",                 "sun",                   "weather"],
  ["słonecznie",             "sunny",                 "weather"],
  ["słowo",                  "word"],
  ["słuchać",                "to listen"],
  ["słyszeć",                "to hear"],
  ["smutny",                 "sad"],
  ["sobota",                 "Saturday",              "calendar"],
  ["sok",                    "juice"],
  ["sól",                    "salt"],
  ["spać",                   "to sleep"],
  ["specjalista",            "specialist"],
  ["spodnie",                "trousers"],
  ["sposób",                 "way / manner"],
  ["spotkać",                "to meet"],
  ["spotykać",               "to meet (regularly)"],
  ["sprawa",                 "matter / affair"],
  ["sprawdzać",              "to check"],
  ["sprawdzić",              "to check (completed)"],
  ["sprawiedliwość",         "justice"],
  ["sprzątać",               "to clean up"],
  ["sprzedawać",             "to sell"],
  ["sprzedawca",             "salesperson"],
  ["srebrny",                "silver"],
  ["stacja",                 "station"],
  ["stać",                   "to stand"],
  ["stary",                  "old"],
  ["statek",                 "ship"],
  ["sterownia",              "control room",          "nuclear"],
  ["stopa",                  "foot"],
  ["stopnie",                "degrees",               "weather"],
  ["stół",                   "table"],
  ["strach",                 "fear"],
  ["strona",                 "side / page"],
  ["student",                "student"],
  ["styczeń",                "January",               "calendar"],
  ["suchy",                  "dry",                   "weather"],
  ["sukienka",               "dress"],
  ["suma",                   "sum"],
  ["swój",                   "one's own"],
  ["syn",                    "son",                   "family"],
  ["sypialnia",              "bedroom"],
  ["szary",                  "gray"],
  ["szczęście",              "happiness / luck"],
  ["szef",                   "boss",                  "nuclear"],
  ["szeroki",                "wide"],
  ["szerokość",              "width"],
  ["szesnaście",             "sixteen"],
  ["sześćdziesiąt",          "sixty"],
  ["szklanka",               "drinking glass"],
  ["szkło",                  "glass"],
  ["szkoła",                 "school"],
  ["szpital",                "hospital"],
  ["sztuczny",               "artificial"],
  ["sztuka",                 "art"],
  ["szukać",                 "to look for"],
  ["szybki",                 "fast"],
  ["szyja",                  "neck"],

  // — Ś —
  ["słońca",                 "sun",                   "weather"],
  ["śmiać się",              "to laugh"],
  ["śmierć",                 "death"],
  ["śniadanie",              "breakfast"],
  ["śnieg",                  "snow",                  "weather"],
  ["śpiewać",                "to sing"],
  ["średnie",                "medium",                "weather"],
  ["środa",                  "Wednesday",             "calendar"],
  ["środek",                 "middle / means"],
  ["świat",                  "world",                 "sports"], 
  ["świeży",                 "fresh"],
  ["świnia",                 "pig"],

  // — T —
  ["ta",                     "this (fem.)"],
  ["taki",                   "such"],
  ["także",                  "also"],
  ["talerz",                 "plate"],
  ["tam",                    "there"],
  ["tamten",                 "that one"],
  ["tani",                   "cheap"],
  ["tańczyć",                "to dance"],
  ["tata",                   "dad",                   "family"],
  ["teatr",                  "theater"],
  ["telefon",                "phone"],
  ["telewizor",              "television"],
  ["temperatura",            "temperature",           "weather"],
  ["ten",                    "this (masc.)"],
  ["też",                    "also / too"],
  ["tłumaczyć",              "to translate / explain"],
  ["to",                     "this / it"],
  ["torba",                  "bag"],
  ["trawa",                  "grass"],
  ["trudny",                 "difficult"],
  ["trzeci",                 "third"],
  ["trzydzieści",            "thirty"],
  ["trzynaście",             "thirteen"],
  ["tu",                     "here"],
  ["tutaj",                  "here"],
  ["twardy",                 "hard"],
  ["twarz",                  "face"],
  ["twój",                   "your"],
  ["ty",                     "you (singular)"],
  ["tydzień",                "week",                  "calendar"],
  ["tylko",                  "only"],

  // — U —
  ["ubranie",                "clothing"],
  ["ucho",                   "ear"],
  ["uczeń",                  "pupil"],
  ["uczyć się",              "to learn / study"],
  ["ulica",                  "street"],
  ["umiarkowana",            "moderate",              "weather"],
  ["umrzeć",                 "to die"],
  ["uniwersytet",            "university"],
  ["usta",                   "mouth"],
  ["używać",                 "to use"],

  // — W —
  ["w",                      "in"],
  ["waga",                   "weight / scale"],
  ["wartość",                "value"],
  ["warunki",                "conditions",            "weather"],
  ["warzywo",                "vegetable"],
  ["wasz",                   "your (plural)"],
  ["ważny",                  "important"],
  ["wąski",                  "narrow"],
  ["wczoraj",                "yesterday",             "calendar"],
  ["według",                 "according to"],
  ["wesoły",                 "cheerful"],
  ["wewnętrzny",             "internal"],
  ["wiara",                  "faith"],
  ["wiatr",                  "wind",                  "weather"],
  ["widelec",                "fork"],
  ["widoczność",             "visibility",            "weather"],
  ["widzieć",                "to see"],
  ["wieczór",                "evening"],
  ["wiedza",                 "knowledge"],
  ["wiedzieć",               "to know (a fact)"],
  ["wiek",                   "century / age"],
  ["wielki",                 "great / huge"],
  ["wielkość",               "size"],
  ["wierzyć",                "to believe"],
  ["wieś",                   "village / countryside"],
  ["więc",                   "so / therefore"],
  ["wilgotność",             "humidity",              "weather"],
  ["wilk",                   "wolf"],
  ["wino",                   "wine"],
  ["wiosna",                 "spring",                "calendar"],
  ["władza",                 "power / authority"],
  ["własny",                 "own"],
  ["włączać",                "to turn on"],
  ["włosy",                  "hair"],
  ["wojna",                  "war"],
  ["wolność",                "freedom"],
  ["wolny",                  "slow / free"],
  ["wracać",                 "to come back"],
  ["wreszcie",               "finally"],
  ["wrócić",                 "to return"],
  ["wrzesień",               "September",             "calendar"],
  ["wschód",                 "east"],
  ["wschód słońca",          "sunrise",               "weather"],
  ["wschód księżyca",        "moonrise",              "weather"],
  ["wstać",                  "to get up"],
  ["wszędzie",               "everywhere"],
  ["wszyscy",                "everyone"],
  ["wszystko",               "everything"],
  ["wśród",                  "among"],
  ["wtedy",                  "then / at that time"],
  ["wtorek",                 "Tuesday",               "calendar"],
  ["wujek",                  "uncle"],
  ["wy",                     "you (plural)"],
  ["wybierać",               "to choose"],
  ["wybrać",                 "to choose (completed)"],
  ["wyłączać",               "to turn off"],
  ["wysoki",                 "tall / high"],
  ["wysokość",               "height"],
  ["wziąć",                  "to take (completed)"],

  // — Z —
  ["z",                      "with / from"],
  ["za",                     "behind / for"],
  ["zachód",                 "west"],
  ["zachód słońca",          "sunset",                "weather"],
  ["zacząć",                 "to begin (completed)"],
  ["zaczynać",               "to begin"],
  ["zajęty",                 "busy"],
  ["zamknięty",              "closed"],
  ["zamykać",                "to close"],
  ["zapomnieć",              "to forget"],
  ["zapytać",                "to ask (completed)"],
  ["zawód",                  "profession",            "nuclear"],
  ["zawsze",                 "always"],
  ["ząb",                    "tooth"],
  ["zbyt",                   "too (excessively)"],
  ["zdjęcie",                "photo"],
  ["zdrowie",                "health"],
  ["zdrowy",                 "healthy"],
  ["zegar",                  "clock"],
  ["zegarek",                "watch"],
  ["zewnętrzny",             "external"],
  ["zielony",                "green"],
  ["zima",                   "winter",                "calendar"],
  ["zimny",                  "cold"],
  ["złoty",                  "gold"],
  ["zły",                    "bad / angry"],
  ["zmieniać",               "to change"],
  ["znać",                   "to know (be familiar)"],
  ["znaleźć",                "to find"],
  ["znowu",                  "again"],
  ["zostać",                 "to stay / become"],
  ["zrobić",                 "to do (completed)"],
  ["zupa",                   "soup"],
  ["zwierzę",                "animal"],

  // — Ż —
  ["żaden",                  "none"],
  ["że",                     "that"],
  ["żeby",                   "so that / in order to"],
  ["zespół",                 "team",                  "sports"],
  ["żołnierz",               "soldier"],
  ["żona",                   "wife",                  "family"],
  ["żółty",                  "yellow"],
  ["życie",                  "life"],
  ["żyć",                    "to live"],
];
(function dedupeCommonWords(){
  const seen=new Set(), keep=[];
  for(const w of COMMON_WORDS){ const k=String(w[0]).toLowerCase(); if(seen.has(k)) continue; seen.add(k); keep.push(w); }
  COMMON_WORDS.length=0; COMMON_WORDS.push(...keep);
})();
