/* =====================================================================
   words.js — your vocabulary bank for Nuklearny Polski
   ---------------------------------------------------------------------
   THIS FILE IS YOURS TO EDIT. The app code lives in index.html and never
   needs to change when you add words here. Just keep both files together
   and upload both when you publish.

   Format:  ["polish", "english", "gender", "emoji", "tag1", "tag2", ...]
            - "polish"/"english": base/dictionary forms, lowercase.
            - Everything after the English is OPTIONAL and recognized by
              what it is, not by position:
                "m" / "f" / "n"  -> noun gender (see GENDER TAGS below)
                an emoji         -> shown on the answer side of the card
                anything else    -> a topic tag (lowercase label like
                                    "weather" that groups words together)
   Example: ["deszcz", "rain", "m", "🌧️", "weather"]
            ["poniedziałek", "Monday", "m", "📅1️⃣", "calendar"]
            ["kot", "cat"]            <- perfectly fine with no extras

   GENDER TAGS (special): "m", "f", "n" mark a noun's gender —
       masculine, feminine, neuter. Put the gender tag right after the
       English, before any topic tags:
         ["burza", "storm", "f", "weather"]
       On flashcards the POLISH side is then colored:
         baby blue = masculine · pink = feminine · pale green = neuter
       Gender tags never appear as filter chips. Leave non-nouns and
       plural-only words (drzwi, spodnie, usta…) untagged.
       Watch the exceptions: mężczyzna, kolega, tata, kierowca,
       specjalista, sprzedawca are MASCULINE despite ending in -a;
       noc, moc, mysz, sól, twarz, wieś… are feminine.

   What topic tags unlock (handled automatically by index.html):
     • In the Word list, search a tag name to see every word carrying it,
       and click a tag chip to filter the table.
     • In Flashcards, pick one or more tags to study just those words —
       e.g. select "calendar" + "weather" to drill both at once.

   Sorted A->Z by the Polish word, with // -- X -- letter dividers.
   To add a word: find its letter, drop in a new line in order, save.
   ===================================================================== */

const COMMON_WORDS = [
  // — A —
  ["a",                      "and / but"],
  ["aby",                    "in order to / so that"],
  ["albo",                   "or"],
  ["ale",                    "but"],
  ["ani",                    "nor"],
  ["apteka",                 "pharmacy",               "f", "💊"],
  ["auto",                   "car, automobile",        "n", "🚗"],
  ["autobus",                "bus",                    "m", "🚌"],
  ["awaria",                 "malfunction / breakdown","f", "🛠️⚠️", "safety", "nuclear"],
  ["aż",                     "until / up to / as many as"],

  // — B —
  ["babcia",                 "grandmother",            "f", "👵", "family"],
  ["bać się",                "to be afraid",           "😨"],
  ["bank",                   "bank",                   "m", "🏦"],
  ["bardzo",                 "very"],
  ["bez",                    "without"],
  ["bezpieczeństwo",         "safety / security",      "n", "🛡️", "safety", "nuclear"],
  ["biały",                  "white",                  "⚪"],
  ["biblioteka",             "library",                "f", "📚"],
  ["biedny",                 "poor",                   "💸"],
  ["bilet",                  "ticket",                 "m", "🎫"],
  ["biuro",                  "office",                 "n", "🏢💼", "nuclear"],
  ["blisko",                 "near",                   "📍🤏"],
  ["błąd ludzki",            "human error",            "m", "👤❌", "handover", "nuclear"],
  ["bo",                     "because"],
  ["bogaty",                 "rich",                   "🤑"],
  ["ból",                    "pain",                   "m", "🤕"],
  ["brat",                   "brother",                "m"],
  ["brązowy",                "brown",                  "🟤"],
  ["brudny",                 "dirty",                  "🦠"],
  ["brzuch",                 "stomach / belly",        "m"],
  ["brzydki",                "ugly",                   "🙈"],
  ["burza",                  "storm",                  "f", "⛈️", "weather"],
  ["buty",                   "shoes",                  "👟"],

  // — C —
  ["cały",                   "whole"],
  ["cel",                    "goal / aim",             "m", "🎯"],
  ["cena",                   "price",                  "f", "💲"],
  ["chleb",                  "bread",                  "m", "🍞"],
  ["chłodny",                "cool",                   "🌬️"],
  ["chłodziwo",              "coolant",                "n", "❄️💧", "nuclear"],
  ["chłopiec",               "boy",                    "m", "👦"],
  ["chmura",                 "cloud",                  "f", "☁️", "weather"],
  ["chociaż",                "although"],
  ["choć",                   "although"],
  ["choroba",                "illness",                "f", "🦠"],
  ["chory",                  "sick",                   "🤒"],
  ["chwila",                 "moment",                 "f", "⏳"],
  ["ciało",                  "body",                   "n", "🧍"],
  ["cichy",                  "quiet",                  "🤫"],
  ["ciekawy",                "interesting",            "🤔✨"],
  ["ciemny",                 "dark",                   "🌑"],
  ["cienki",                 "thin"],
  ["ciepły",                 "warm",                   "♨️", "weather"],
  ["cieszyć się",            "to be glad",             "😄"],
  ["ciężki",                 "heavy / hard",           "🏋️"],
  ["ciocia",                 "aunt",                   "f", "family"],
  ["ciśnienie",              "pressure",               "n", "⏲️💨", "nuclear", "weather"],
  ["co",                     "what",                   "❓"],
  ["coś",                    "something"],
  ["córka",                  "daughter",               "f", "👧", "family"],
  ["cukier",                 "sugar",                  "m", "🍬"],
  ["czapka",                 "cap",                    "f", "🧢"],
  ["czarny",                 "black",                  "⚫"],
  ["czas",                   "time",                   "m", "⏳"],
  ["czasem",                 "sometimes"],
  ["czemu",                  "why / what for"],
  ["czerwiec",               "June",                   "m", "☀️🗓️", "calendar"],
  ["czerwony",               "red",                    "🔴"],
  ["Cześć",                  "Hi / Bye (informal)",    "👋", "greetings"],
  ["często",                 "often"],
  ["część",                  "part",                   "f"],
  ["człowiek",               "person / human",         "m", "🧍"],
  ["czterdzieści",           "forty",                  "4️⃣0️⃣"],
  ["czternaście",            "fourteen",               "1️⃣4️⃣"],
  ["cztery",                 "4",                      "4️⃣", "numbers"],
  ["czujnik",                "sensor",                 "m", "📡", "nuclear"],
  ["czujność",               "vigilance / alertness",  "f", "👀", "handover", "nuclear"],
  ["czwartek",               "Thursday",               "m", "📅4️⃣", "calendar"],
  ["czy",                    "whether"],
  ["Czy mówi pan po angielsku?","Do you speak English? (to a man)","🇬🇧❓", "greetings", "phrase"],
  ["czyj",                   "whose"],
  ["czynnik ludzki",         "human factor",           "m", "👤⚙️", "handover", "nuclear"],
  ["czysty",                 "clean",                  "✨🧼"],
  ["ćwierćfinał",            "quarterfinal",           "m", "🏆", "sports"],

  // — D —
  ["daleko",                 "far",                    "📍🔭"],
  ["data",                   "date",                   "f", "📅", "calendar"],
  ["deszcz",                 "rain",                   "m", "🌧️", "weather"],
  ["dla",                    "for"],
  ["dlaczego",               "why",                    "🤷❓"],
  ["długi",                  "long",                   "📏"],
  ["długopis",               "pen",                    "m", "🖊️"],
  ["długość",                "length",                 "f", "📏"],
  ["dnia",                   "on"],
  ["do",                     "to / into"],
  ["do ustalenia",           "to be determined",       "sports"],
  ["Do widzenia",            "Goodbye",                "👋🚪", "greetings", "phrase"],
  ["dobry",                  "good",                   "👍"],
  ["Dobry wieczór",          "Good evening",           "🌆👋", "greetings", "phrase"],
  ["dokąd",                  "where to"],
  ["dolny",                  "lower",                  "⬇️"],
  ["dom",                    "house / home",           "m", "🏠"],
  ["dość",                   "enough / quite"],
  ["dozymetr",               "dosimeter",              "m", "📟☢️", "safety", "nuclear"],
  ["drewno",                 "wood",                   "n", "🪵"],
  ["droga",                  "road / way",             "f", "🛣️"],
  ["drogi",                  "expensive / dear",       "💎💰"],
  ["drugi",                  "second",                 "🥈"],
  ["drzewo",                 "tree",                   "n", "🌳"],
  ["drzwi",                  "door",                   "🚪"],
  ["duży",                   "big",                    "🐘"],
  ["dwa",                    "2",                      "2️⃣", "numbers"],
  ["dwadzieścia",            "twenty",                 "2️⃣0️⃣"],
  ["dwanaście",              "twelve",                 "1️⃣2️⃣"],
  ["dworzec",                "station (rail/bus)",     "m", "🚉"],
  ["dyrektor",               "director",               "m", "nuclear"],
  ["dziadek",                "grandfather",            "m", "👴"],
  ["dzieci",                 "children",               "👧👦"],
  ["dziecko",                "child",                  "n", "🧒"],
  ["dzień",                  "day",                    "m", "☀️📅", "calendar"],
  ["Dzień dobry",            "Good morning / Good day","🌅👋", "greetings", "phrase"],
  ["dziesięć",               "10",                     "🔟", "numbers"],
  ["dziewczyna",             "girl",                   "f", "👧"],
  ["dziewięć",               "9",                      "9️⃣", "numbers"],
  ["dziewięćdziesiąt",       "ninety",                 "9️⃣0️⃣"],
  ["dziewiętnaście",         "nineteen",               "1️⃣9️⃣"],
  ["Dziękuję",               "Thank you",              "😊🙏", "greetings"],
  ["dzisiaj / dziś",         "today",                  "📅", "calendar"],

  // — E —
  ["edukacja",               "education",              "f", "📚🎓"],
  ["ekspert",                "expert",                 "m", "🧠"],
  ["elektrownia",            "power plant",            "f", "🏭⚡", "nuclear"],
  ["elektrownia jądrowa",    "nuclear power plant",    "f", "⚛️🏭", "nuclear"],
  ["energia",                "energy",                 "f", "⚡", "nuclear"],
  ["ewakuacja",              "evacuation",             "f", "🏃🚪", "safety"],
  // — F —
  ["filiżanka",              "cup",                    "f", "☕"],
  ["film",                   "film",                   "m", "🎬"],
  ["fioletowy",              "purple",                 "🟣"],
  ["firma",                  "company",                "f", "🏢", "nuclear"],
  // — G —
  ["gaśnica",                "fire extinguisher",      "f", "🧯", "safety"],
  ["gazeta",                 "newspaper",              "f", "📰"],
  ["gdy",                    "when"],
  ["gdzie",                  "where",                  "📍❓"],
  ["Gdzie jest wyjście?",    "Where is the exit?",     "🚪❓", "everyday", "phrase"],
  ["Gdzie jest…?",           "Where is…?",             "📍❓", "everyday", "phrase"],
  ["głośny",                 "loud",                   "🔊"],
  ["głowa",                  "head",                   "f", "👤"],
  ["główny",                 "main",                   "🎯"],
  ["godzina",                "hour",                   "f", "🕐", "numbers", "calendar"],
  ["godzinowa",              "hourly",                 "calendar"],
  ["gorący",                 "hot",                    "🥵🔥", "weather"],
  ["gorzki",                 "bitter",                 "😖☕"],
  ["gospodarka",             "economy",                "f", "📈"],
  ["gość",                   "guest",                  "m"],
  ["gotowy",                 "ready",                  "🏁"],
  ["góra",                   "mountain",               "f", "⛰️"],
  ["górny",                  "upper",                  "⬆️"],
  ["granica",                "border",                 "f", "🛂"],
  ["gruby",                  "thick / fat"],
  ["grudzień",               "December",               "m", "🎄🗓️", "calendar"],
  ["gwiazda",                "star",                   "f", "⭐"],
  // — H —
  ["herbata",                "tea",                    "f", "🍵", "everyday"],
  ["historia",               "history / story",        "f", "📜"],
  ["hotel",                  "hotel",                  "m", "🏨"],
  // — I —
  ["i",                      "and"],
  ["ich",                    "their"],
  ["ile",                    "how much / how many",    "🔢❓"],
  ["Ile to kosztuje?",       "How much is it?",        "💲❓", "everyday", "phrase"],
  ["ilość",                  "quantity",               "f"],
  ["inny",                   "other"],
  ["interfejs człowiek–maszyna","human–machine interface","m", "👤🤖", "handover", "nuclear"],
  ["inżynier",               "engineer",               "m", "👷", "nuclear"],
  // — J —
  ["ja",                     "I",                      "🙋"],
  ["jabłko",                 "apple",                  "n", "🍎"],
  ["jajko",                  "egg",                    "n", "🥚"],
  ["jak",                    "how"],
  ["jaki",                   "what kind of"],
  ["jako",                   "as"],
  ["jakość",                 "quality",                "f", "⭐", "weather"],
  ["jakość",                 "quality",                "f", "⭐"],
  ["jasny",                  "bright / light",         "💡"],
  ["jądrowy",                "nuclear",                "⚛️", "nuclear"],
  ["jeden",                  "1",                      "1️⃣", "numbers"],
  ["jedenaście",             "eleven",                 "1️⃣1️⃣"],
  ["jedzenie",               "food",                   "n", "🍽️🍲", "everyday"],
  ["jego",                   "his"],
  ["jej",                    "her"],
  ["jesień",                 "autumn",                 "f", "🍂", "calendar"],
  ["jeszcze",                "still / yet"],
  ["jeśli",                  "if"],
  ["jezioro",                "lake",                   "n", "🏞️"],
  ["jeżeli",                 "if"],
  ["język",                  "language / tongue",      "m", "👅💬"],
  ["jutro",                  "tomorrow",               "📅▶️", "calendar"],
  ["już",                    "already"],

  // — K —
  ["kalendarz",              "calendar",               "m", "🗓️", "calendar"],
  ["kamień",                 "stone",                  "m", "🪨"],
  ["karta",                  "card",                   "f", "💳"],
  ["kask",                   "hard hat / helmet",      "m", "⛑️", "safety"],
  ["kawa",                   "coffee",                 "f", "☕", "everyday"],
  ["kawiarnia",              "café",                   "f", "☕"],
  ["każdy",                  "each / every"],
  ["kiedy",                  "when",                   "🕐❓"],
  ["kierowca",               "driver",                 "m", "🚗🧑"],
  ["kierownik",              "manager",                "m", "nuclear"],
  ["kierunek",               "direction",              "m", "weather"],
  ["kino",                   "cinema",                 "n", "🎬"],
  ["klient",                 "customer",               "m", "🛍️"],
  ["klucz",                  "key",                    "m", "🔑"],
  ["kłamstwo",               "lie",                    "n", "🤥"],
  ["kobieta",                "woman",                  "f", "👩"],
  ["kolacja",                "supper",                 "f", "🌙🍽️"],
  ["kolega",                 "colleague / friend (m)", "m"],
  ["koleżanka",              "friend (f)",             "f"],
  ["kolor",                  "color",                  "m", "🎨"],
  ["komputer",               "computer",               "m", "💻", "nuclear"],
  ["koniec",                 "end",                    "m", "🔚"],
  ["koniec",                 "finish",                 "m", "🔚", "sports"],
  ["konserwacja",            "maintenance",            "f", "🔧", "handover", "nuclear"],
  ["koń",                    "horse",                  "m", "🐴"],
  ["koszt",                  "cost",                   "m", "🧾"],
  ["koszula",                "shirt",                  "f", "👔"],
  ["kościół",                "church",                 "m", "⛪"],
  ["kość",                   "bone",                   "f", "🦴"],
  ["kot",                    "cat",                    "m", "🐈"],
  ["kraj",                   "country",                "m", "🗺️🚩"],
  ["krew",                   "blood",                  "f", "🩸"],
  ["krowa",                  "cow",                    "f", "🐄"],
  ["król",                   "king",                   "m", "👑"],
  ["krótki",                 "short",                  "🤏"],
  ["krzesło",                "chair",                  "n", "🪑"],
  ["książka",                "book",                   "f", "📖"],
  ["księżyc",                "moon",                   "m", "🌙"],
  ["kto",                    "who",                    "👤❓"],
  ["ktoś",                   "someone"],
  ["Która godzina?",         "What time is it?",       "🕐❓", "numbers", "phrase"],
  ["który",                  "which"],
  ["kuchnia",                "kitchen",                "f", "🍳"],
  ["kultura",                "culture",                "f", "🎭"],
  ["kurtka",                 "jacket",                 "f", "🧥"],
  ["kwaśny",                 "sour",                   "🍋"],
  ["kwiat",                  "flower",                 "m", "🌸"],
  ["kwiecień",               "April",                  "m", "🌷🗓️", "calendar"],
  // — L —
  ["lampa",                  "lamp",                   "f", "💡"],
  ["las",                    "forest",                 "m", "🌲🌲"],
  ["lato",                   "summer",                 "n", "☀️", "calendar"],
  ["lekarz",                 "doctor",                 "m", "🧑‍⚕️"],
  ["lekki",                  "light",                  "🪶"],
  ["lew",                    "lion",                   "m", "🦁"],
  ["lewo",                   "left",                   "⬅️", "everyday"],
  ["lewy",                   "left (side)",            "👈"],
  ["liczba",                 "number",                 "f", "🔢"],
  ["lipiec",                 "July",                   "m", "☀️🗓️", "calendar"],
  ["list",                   "letter",                 "m", "✉️"],
  ["lista kontrolna",        "checklist",              "f", "☑️📋", "handover", "nuclear"],
  ["listopad",               "November",               "m", "🌧️🗓️", "calendar"],
  ["liść",                   "leaf",                   "m", "🍃"],
  ["litera",                 "letter (character)",     "f", "🔤"],
  ["lotnisko",               "airport",                "n", "✈️"],
  ["lód",                    "ice",                    "m", "🧊", "nuclear"],
  ["lub",                    "or"],
  ["ludzie",                 "people",                 "👥"],
  ["luty",                   "February",               "m", "❄️🗓️", "calendar"],
  // — Ł —
  ["ładny",                  "pretty",                 "✨"],
  ["łatwy",                  "easy",                   "🍰"],
  ["łazienka",               "bathroom",               "f", "🛁"],
  ["łóżko",                  "bed",                    "n", "🛏️"],
  ["łyżka",                  "spoon",                  "f", "🥄"],
  // — M —
  ["maj",                    "May",                    "m", "🌸🗓️", "calendar"],
  ["mały",                   "small",                  "🐜"],
  ["mama",                   "mom",                    "f", "👩"],
  ["marzec",                 "March",                  "m", "🌱🗓️", "calendar"],
  ["matka",                  "mother",                 "f", "👩‍👧", "family"],
  ["mąż",                    "husband",                "m", "🤵", "family"],
  ["metal",                  "metal",                  "m", "⚙️"],
  ["mężczyzna",              "man",                    "m", "👨"],
  ["mgła",                   "fog",                    "f", "🌫️", "weather"],
  ["miasto",                 "city / town",            "n", "🏙️"],
  ["miejsce",                "place",                  "n", "📍"],
  ["miesiąc",                "month",                  "m", "🗓️", "calendar"],
  ["mieszkanie",             "apartment",              "n", "🏢"],
  ["między",                 "between"],
  ["miękki",                 "soft",                   "🧸"],
  ["mięso",                  "meat",                   "n", "🥩"],
  ["milion",                 "million",                "m", "💰💰💰"],
  ["miłość",                 "love",                   "f", "💕"],
  ["miły",                   "nice / kind",            "😊"],
  ["mimo",                   "despite"],
  ["minuta",                 "minute",                 "f", "⏱️", "numbers", "calendar"],
  ["mistrzostwa",            "championships",          "🏆🥇", "sports"],
  ["mleko",                  "milk",                   "n", "🥛"],
  ["młody",                  "young",                  "👶"],
  ["moc",                    "power",                  "f", "⚡💪"],
  ["mocny",                  "strong",                 "💪"],
  ["mokry",                  "wet",                    "💦"],
  ["morze",                  "sea",                    "n", "🌊🚢"],
  ["most",                   "bridge",                 "m", "🌉"],
  ["może",                   "maybe"],
  ["możliwy",                "possible"],
  ["mój",                    "my"],
  ["mózg",                   "brain",                  "m", "🧠"],
  ["muzeum",                 "museum",                 "n", "🏛️"],
  ["muzyka",                 "music",                  "f", "🎵"],
  ["my",                     "we"],
  ["mysz",                   "mouse",                  "f", "🐭"],
  ["myśl",                   "thought",                "f", "💭"],
  // — N —
  ["na",                     "on"],
  ["nad",                    "above / over"],
  ["nadchodzące",            "upcoming",               "sports"],
  ["nadzieja",               "hope",                   "f", "🕊️"],
  ["najpierw",               "first / at first"],
  ["nastawnia",              "control room",           "f", "🎛️", "nuclear"],
  ["następny",               "next",                   "⏭️"],
  ["nasz",                   "our"],
  ["naturalny",              "natural",                "🌿"],
  ["nauczyciel",             "teacher",                "m", "🧑‍🏫"],
  ["nauka",                  "science / learning",     "f", "🔬"],
  ["naukowiec",              "scientist",              "m", "🧑‍🔬"],
  ["nawet",                  "even"],
  ["Nazywam się…",           "My name is…",            "👤🏷️", "greetings", "phrase"],
  ["nic",                    "nothing"],
  ["Nie",                    "No",                     "👎", "greetings"],
  ["Nie rozumiem",           "I don't understand",     "😕❓", "greetings", "phrase"],
  ["niebezpieczeństwo",      "danger",                 "n", "⚠️", "safety", "nuclear"],
  ["niebieski",              "blue",                   "🔵"],
  ["niebo",                  "sky / heaven",           "n", "🌌", "weather"],
  ["niedziela",              "Sunday",                 "f", "📅7️⃣", "calendar"],
  ["niedźwiedź",             "bear",                   "m", "🐻"],
  ["nigdy",                  "never"],
  ["nikt",                   "nobody"],
  ["niski",                  "low / short",            "⬇️", "weather"],
  ["niż",                    "than"],
  ["noc",                    "night",                  "f", "🌃"],
  ["noga",                   "leg / foot",             "f", "🦵"],
  ["nos",                    "nose",                   "m", "👃"],
  ["nowy",                   "new",                    "✨"],
  ["nóż",                    "knife",                  "m", "🔪"],
  ["nudny",                  "boring",                 "🥱"],
  ["numer",                  "number (id)",            "m", "#️⃣"],
  // — O —
  ["o",                      "about"],
  ["obciążenie pracą",       "workload",               "n", "💼⚖️", "handover", "nuclear"],
  ["obiad",                  "lunch / dinner",         "m", "🍽️"],
  ["obok",                   "beside"],
  ["obraz",                  "picture / painting",     "m", "🖼️"],
  ["od",                     "from"],
  ["odczuwalna",             "perceptible/perceived",  "weather"],
  ["odpowiedź",              "answer",                 "f", "✅💬"],
  ["ogień",                  "fire",                   "m", "🔥"],
  ["ogród",                  "garden",                 "m", "🌷🌳"],
  ["ojciec",                 "father",                 "👨‍👦"],
  ["okno",                   "window",                 "n", "🪟"],
  ["oko",                    "eye",                    "n", "👁️"],
  ["okolica",                "area / surroundings",    "f"],
  ["około",                  "around / about"],
  ["ołówek",                 "pencil",                 "m", "✏️"],
  ["on",                     "he",                     "👨"],
  ["ona",                    "she",                    "👩"],
  ["one",                    "they (non-male)"],
  ["oni",                    "they (men/mixed)"],
  ["ono",                    "it"],
  ["opady",                  "precipitation",          "🌧️❄️", "weather"],
  ["opcje",                  "options"],
  ["operator",               "operator",               "m", "🧑‍💻", "nuclear"],
  ["oprócz",                 "besides / except"],
  ["oraz",                   "as well as"],
  ["osiem",                  "8",                      "8️⃣", "numbers"],
  ["osiemdziesiąt",          "eighty",                 "8️⃣0️⃣"],
  ["osiemnaście",            "eighteen",               "1️⃣8️⃣"],
  ["osobno",                 "separately"],
  ["ostatni",                "last",                   "🔚"],
  ["ostry",                  "sharp",                  "🔪"],
  ["ostrzeżenie",            "warning",                "n", "⚠️", "safety"],
  ["oświetlenie",            "lightning",              "n", "⚡", "weather"],
  ["otwarty",                "open",                   "🔓"],
  ["owca",                   "sheep",                  "f", "🐑"],
  ["owoc",                   "fruit",                  "m", "🍎🍌"],
  // — P —
  ["palec",                  "finger",                 "m", "☝️"],
  ["państwo",                "state / country",        "n", "🏛️🗺️"],
  ["papier",                 "paper",                  "m", "📄"],
  ["para",                   "pair",                   "f", "✌️"],
  ["park",                   "park",                   "m", "🌳"],
  ["październik",            "October",                "m", "🍁🗓️", "calendar"],
  ["pełnia księżyca",        "full moon",              "f", "🌕", "weather"],
  ["pełny",                  "full",                   "🔋"],
  ["pewny",                  "sure / certain",         "✔️"],
  ["piątek",                 "Friday",                 "m", "📅5️⃣", "calendar"],
  ["pielęgniarka",           "nurse",                  "f", "👩‍⚕️"],
  ["pieniądze",              "money",                  "💰"],
  ["pierwszy",               "first",                  "🥇"],
  ["pies",                   "dog",                    "m", "🐕"],
  ["pięć",                   "5",                      "5️⃣", "numbers"],
  ["pięćdziesiąt",           "fifty",                  "5️⃣0️⃣"],
  ["piękny",                 "beautiful",              "😍"],
  ["piętnaście",             "fifteen",                "1️⃣5️⃣"],
  ["piosenka",               "song",                   "f", "🎤🎵"],
  ["piwo",                   "beer",                   "n", "🍺"],
  ["plac",                   "square",                 "m"],
  ["plecy",                  "back"],
  ["płaszcz",                "coat",                   "m", "🧥🧣"],
  ["po",                     "after"],
  ["pochmurnie",             "cloudy",                 "☁️☁️", "weather"],
  ["pociąg",                 "train",                  "m", "🚆"],
  ["początek",               "beginning",              "m", "▶️"],
  ["poczta",                 "post office",            "f", "📮"],
  ["pod",                    "under"],
  ["podczas",                "during"],
  ["podobny",                "similar",                "👯"],
  ["podsumowanie",           "summary",                "n", "📋"],
  ["pogoda",                 "weather",                "f", "🌤️", "weather"],
  ["pokój",                  "room / peace",           "m", "🚪🛋️"],
  ["pole",                   "field",                  "n", "🌾"],
  ["policjant",              "police officer",         "m", "👮"],
  ["polityka",               "politics",               "f", "🗳️"],
  ["połowa",                 "half",                   "f", "🌓"],
  ["południe",               "noon / south",           "n", "🕛"],
  ["pomarańczowy",           "orange",                 "🟠"],
  ["Pomocy!",                "Help!",                  "🆘", "everyday", "phrase"],
  ["pompa",                  "pump",                   "f", "💧🔄", "nuclear"],
  ["pomysł",                 "idea",                   "m", "💡"],
  ["poniedziałek",           "Monday",                 "m", "📅1️⃣", "calendar"],
  ["ponieważ",               "because"],
  ["popołudnie",             "afternoon",              "n", "🕒"],
  ["poprzedni",              "previous",               "⏮️"],
  ["porywy",                 "gusts",                  "💨💨", "weather"],
  ["potem",                  "then / afterwards"],
  ["Potwierdzam",            "I confirm / Confirmed",  "👍✅", "handover", "phrase"],
  ["powietrze",              "air",                    "n", "💨", "weather"],
  ["powód",                  "reason",                 "m"],
  ["poziom",                 "level",                  "m", "📊", "nuclear"],
  ["pożar",                  "fire",                   "m", "🔥", "safety"],
  ["praca",                  "work / job",             "f", "💼"],
  ["pracownik",              "worker / employee",      "m", "🧑‍💼"],
  ["prawda",                 "truth",                  "f", "✅"],
  ["prawdziwy",              "real / true",            "✅"],
  ["prawo",                  "law / right",            "n"],
  ["prawy",                  "right (side)",           "👉"],
  ["prezent",                "gift",                   "m", "🎁"],
  ["prezydent",              "president",              "m", "🏛️"],
  ["pręty sterujące",        "control rods",           "⚛️🎚️", "nuclear"],
  ["problem",                "problem",                "m", "⚠️"],
  ["procedura",              "procedure",              "f", "📋", "handover", "nuclear"],
  ["promieniowanie",         "radiation",              "n", "☢️", "safety", "nuclear"],
  ["prosto",                 "straight ahead",         "⬆️", "everyday"],
  ["prosty",                 "simple / straight",      "➡️"],
  ["Proszę",                 "Please / You're welcome / Here you go","🙏", "greetings"],
  ["prywatny",               "private",                "🤫"],
  ["przed",                  "before / in front of"],
  ["przekazanie zmiany",     "shift handover",         "n", "🤝🔄", "handover", "nuclear", "phrase"],
  ["przełącznik",            "switch",                 "m", "🎚️", "nuclear"],
  ["przemysł",               "industry",               "m", "🏭"],
  ["przepływ",               "flow",                   "m", "➡️💧", "nuclear"],
  ["Przepraszam",            "Excuse me / Sorry",      "🙇", "greetings"],
  ["przez",                  "through / by"],
  ["przy",                   "next to"],
  ["przycisk",               "button",                 "m", "🔘", "nuclear"],
  ["przyjaciel",             "friend",                 "m", "🤝"],
  ["przyjaźń",               "friendship",             "f", "🤝💛"],
  ["przykład",               "example",                "m"],
  ["przystanek",             "(bus/tram) stop",        "m", "🚏"],
  ["ptak",                   "bird",                   "m", "🐦"],
  ["publiczny",              "public",                 "🏛️👥"],
  ["pulpit sterowniczy",     "control desk / panel",   "m", "🎛️🔘", "nuclear"],
  ["pusty",                  "empty",                  "🪫"],
  ["pytanie",                "question",               "n", "❓"],
  // — R —
  ["rano",                   "morning",                "🌅"],
  ["raport",                 "report",                 "m", "📊", "handover", "nuclear"],
  ["raz",                    "once / one time",        "1️⃣"],
  ["razem",                  "together"],
  ["reaktor",                "reactor",                "m", "⚛️", "nuclear"],
  ["reaktor jądrowy",        "nuclear reactor",        "m", "⚛️", "nuclear"],
  ["region",                 "region",                 "m", "🗺️"],
  ["religia",                "religion",               "f", "🙏⛪"],
  ["restauracja",            "restaurant",             "f", "🍽️"],
  ["ręka",                   "hand / arm",             "f", "✋"],
  ["rodzina",                "family",                 "f", "👨‍👩‍👧‍👦", "family"],
  ["rok",                    "year",                   "m", "📅", "calendar"],
  ["roślina",                "plant",                  "f", "🪴"],
  ["rower",                  "bicycle",                "m", "🚲"],
  ["równy",                  "equal",                  "⚖️"],
  ["różny",                  "different",              "🔀"],
  ["różowy",                 "pink",                   "🌸"],
  ["ryba",                   "fish",                   "f", "🐟"],
  ["rynek",                  "market square",          "m", "🛍️"],
  ["rzadko",                 "rarely"],
  ["rząd",                   "government",             "m", "🏛️"],
  ["rzecz",                  "thing",                  "f", "📦"],
  ["rzeczywista",            "actual"],
  ["rzeka",                  "river",                  "f", "🌊"],
  // — S —
  ["sam",                    "alone / oneself"],
  ["samochód",               "car",                    "m", "🚗"],
  ["samolot",                "airplane",               "m", "✈️"],
  ["sąsiad",                 "neighbor",               "m", "🏘️"],
  ["sekunda",                "second",                 "f", "⚡⏱️"],
  ["ser",                    "cheese",                 "m", "🧀"],
  ["serce",                  "heart",                  "n", "❤️"],
  ["siebie",                 "oneself"],
  ["siedem",                 "7",                      "7️⃣", "numbers"],
  ["siedemdziesiąt",         "seventy",                "7️⃣0️⃣"],
  ["siedemnaście",           "seventeen",              "1️⃣7️⃣"],
  ["sierpień",               "August",                 "m", "🌻🗓️", "calendar"],
  ["siła",                   "strength / force",       "f", "💪"],
  ["siostra",                "sister",                 "f"],
  ["skąd",                   "where from"],
  ["sklep",                  "shop",                   "m", "🏪"],
  ["skóra",                  "skin",                   "f"],
  ["słaby",                  "weak",                   "🥀"],
  ["słodki",                 "sweet",                  "🍭"],
  ["słonecznie",             "sunny",                  "☀️", "weather"],
  ["słony",                  "salty",                  "🧂"],
  ["słoń",                   "elephant",               "m", "🐘"],
  ["słońce",                 "sun",                    "n", "☀️", "weather"],
  ["słowo",                  "word",                   "n", "💬"],
  ["smutny",                 "sad",                    "😢"],
  ["sobota",                 "Saturday",               "f", "📅6️⃣", "calendar"],
  ["sok",                    "juice",                  "m", "🧃"],
  ["sól",                    "salt",                   "f", "🧂"],
  ["specjalista",            "specialist",             "m"],
  ["spodnie",                "trousers",               "👖"],
  ["sposób",                 "way / manner",           "m"],
  ["sprawa",                 "matter / affair",        "f"],
  ["sprawiedliwość",         "justice",                "f", "⚖️"],
  ["sprzedawca",             "salesperson",            "m", "🛒"],
  ["srebrny",                "silver",                 "🥈"],
  ["stacja",                 "station",                "f", "🚉"],
  ["stary",                  "old",                    "👴"],
  ["statek",                 "ship",                   "m", "🚢"],
  ["sterownia",              "control room",           "f", "🎛️", "nuclear"],
  ["sto",                    "100",                    "💯", "numbers"],
  ["Stop!",                  "Stop!",                  "🛑", "safety", "phrase"],
  ["stopa",                  "foot",                   "f", "🦶"],
  ["stopnie",                "degrees",                "🌡️", "weather"],
  ["stół",                   "table",                  "m"],
  ["strach",                 "fear",                   "m", "😱"],
  ["strona",                 "side / page",            "f", "📄"],
  ["student",                "student",                "m", "🎓"],
  ["styczeń",                "January",                "m", "❄️🗓️", "calendar"],
  ["suchy",                  "dry",                    "🏜️", "weather"],
  ["sukienka",               "dress",                  "f", "👗"],
  ["suma",                   "sum",                    "f", "➕"],
  ["swój",                   "one's own"],
  ["syn",                    "son",                    "m", "👦", "family"],
  ["sypialnia",              "bedroom",                "f", "🛏️"],
  ["szary",                  "gray",                   "🩶"],
  ["szczęście",              "happiness / luck",       "n", "🍀"],
  ["szef",                   "boss",                   "m", "👔", "nuclear"],
  ["szeroki",                "wide",                   "↔️"],
  ["szerokość",              "width",                  "f", "↔️"],
  ["szesnaście",             "sixteen",                "1️⃣6️⃣"],
  ["sześć",                  "6",                      "6️⃣", "numbers"],
  ["sześćdziesiąt",          "sixty",                  "6️⃣0️⃣"],
  ["szklanka",               "drinking glass",         "f", "🥤"],
  ["szkło",                  "glass",                  "n", "🥂"],
  ["szkoła",                 "school",                 "f", "🏫"],
  ["szpital",                "hospital",               "m", "🏥"],
  ["sztuczny",               "artificial",             "🤖"],
  ["sztuka",                 "art",                    "f", "🎨"],
  ["szybki",                 "fast",                   "🚀"],
  ["szyja",                  "neck",                   "f"],
  // — Ś —
  ["słońca",                 "sun",                    "☀️", "weather"],
  ["śmierć",                 "death",                  "f", "💀"],
  ["śniadanie",              "breakfast",              "n", "🍳"],
  ["śnieg",                  "snow",                   "m", "❄️", "weather"],
  ["średnie",                "medium",                 "weather"],
  ["środa",                  "Wednesday",              "f", "📅3️⃣", "calendar"],
  ["środek",                 "middle / means",         "m"],
  ["świat",                  "world",                  "m", "🌍", "sports"],
  ["świeży",                 "fresh",                  "🥬"],
  ["świnia",                 "pig",                    "f", "🐷"],
  // — T —
  ["ta",                     "this (fem.)"],
  ["Tak",                    "Yes",                    "👍", "greetings"],
  ["taki",                   "such"],
  ["także",                  "also"],
  ["talerz",                 "plate",                  "m", "🍽️"],
  ["tam",                    "there",                  "👉📍"],
  ["tamten",                 "that one"],
  ["tani",                   "cheap",                  "🏷️"],
  ["tata",                   "dad",                    "m", "👨", "family"],
  ["teatr",                  "theater",                "m", "🎭"],
  ["telefon",                "phone",                  "m", "📱"],
  ["telewizor",              "television",             "m", "📺"],
  ["temperatura",            "temperature",            "f", "🌡️", "weather"],
  ["ten",                    "this (masc.)"],
  ["teraz",                  "now",                    "⏰", "calendar"],
  ["też",                    "also / too"],
  ["to",                     "this / it"],
  ["toaleta / ubikacja",     "toilet / restroom",      "f", "🚻", "everyday"],
  ["torba",                  "bag",                    "f", "👜"],
  ["trawa",                  "grass",                  "f", "🌱"],
  ["trudny",                 "difficult",              "🧗"],
  ["trzeci",                 "third",                  "🥉"],
  ["trzy",                   "3",                      "3️⃣", "numbers"],
  ["trzydzieści",            "thirty",                 "3️⃣0️⃣"],
  ["trzynaście",             "thirteen",               "1️⃣3️⃣"],
  ["tu",                     "here",                   "📍"],
  ["tutaj",                  "here",                   "📍"],
  ["twardy",                 "hard",                   "🪨"],
  ["twarz",                  "face",                   "f", "🙂"],
  ["twój",                   "your"],
  ["ty",                     "you (singular)",         "👉"],
  ["tydzień",                "week",                   "m", "📅7️⃣", "calendar"],
  ["tylko",                  "only"],
  ["tysiąc",                 "1000",                   "m", "💯0️⃣", "numbers"],

  // — U —
  ["ubranie",                "clothing",               "n", "👕"],
  ["ucho",                   "ear",                    "n", "👂"],
  ["uczeń",                  "pupil",                  "m", "🧑‍🎓"],
  ["ulica",                  "street",                 "f", "🚦"],
  ["umiarkowana",            "moderate",               "weather"],
  ["uniwersytet",            "university",             "m", "🎓🏛️"],
  ["usta",                   "mouth",                  "👄"],
  ["usterka",                "fault / defect",         "f", "⚙️❌", "handover", "nuclear"],
  ["Uwaga!",                 "Caution! / Attention!",  "📢⚠️", "safety", "phrase"],

  // — W —
  ["w",                      "in"],
  ["waga",                   "weight / scale",         "f", "⚖️"],
  ["wartość",                "value",                  "f", "💎"],
  ["warunki",                "conditions",             "weather"],
  ["warzywo",                "vegetable",              "n", "🥕"],
  ["wasz",                   "your (plural)"],
  ["ważny",                  "important",              "❗"],
  ["wąski",                  "narrow"],
  ["wczoraj",                "yesterday",              "◀️📅", "calendar"],
  ["według",                 "according to"],
  ["wesoły",                 "cheerful",               "😄"],
  ["wewnętrzny",             "internal"],
  ["wiara",                  "faith",                  "f", "🙏"],
  ["wiatr",                  "wind",                   "m", "💨", "weather"],
  ["widelec",                "fork",                   "m", "🍴"],
  ["widoczność",             "visibility",             "f", "👁️🌫️", "weather"],
  ["wieczór",                "evening",                "m", "🌆"],
  ["wiedza",                 "knowledge",              "f", "🧠📚"],
  ["wiek",                   "century / age",          "m", "⏳"],
  ["wielki",                 "great / huge",           "🏔️"],
  ["wielkość",               "size",                   "f"],
  ["wieś",                   "village / countryside",  "f", "🏡🌾"],
  ["więc",                   "so / therefore"],
  ["wilgotność",             "humidity",               "f", "💦", "weather"],
  ["wilk",                   "wolf",                   "m", "🐺"],
  ["wino",                   "wine",                   "n", "🍷"],
  ["wiosna",                 "spring",                 "f", "🌷", "calendar"],
  ["władza",                 "power / authority",      "f", "🏛️👑"],
  ["własny",                 "own"],
  ["włosy",                  "hair",                   "💇"],
  ["woda",                   "water",                  "f", "💧", "everyday"],
  ["wojna",                  "war",                    "f", "⚔️"],
  ["wolność",                "freedom",                "f", "🗽"],
  ["wolny",                  "slow / free",            "🐢"],
  ["wreszcie",               "finally"],
  ["wrzesień",               "September",              "m", "🍂🗓️", "calendar"],
  ["wschód",                 "east",                   "m", "🧭➡️"],
  ["wschód księżyca",        "moonrise",               "m", "🌙⬆️", "weather"],
  ["wschód słońca",          "sunrise",                "m", "🌅", "weather"],
  ["wskaźnik",               "indicator / gauge",      "m", "📟", "nuclear"],
  ["wszędzie",               "everywhere",             "🌍📍"],
  ["wszyscy",                "everyone"],
  ["wszystko",               "everything"],
  ["wśród",                  "among"],
  ["wtedy",                  "then / at that time"],
  ["wtorek",                 "Tuesday",                "m", "📅2️⃣", "calendar"],
  ["wujek",                  "uncle",                  "m"],
  ["wy",                     "you (plural)"],
  ["wyjście awaryjne",       "emergency exit",         "n", "🚨🚪", "safety"],
  ["wyłączenie awaryjne",    "emergency shutdown (scram)","n", "🛑⚛️", "safety", "nuclear"],
  ["wypadek",                "accident",               "m", "💥🚑", "safety"],
  ["wysoki",                 "tall / high",            "🦒"],
  ["wysokość",               "height",                 "f", "⬆️📏"],
  // — Z —
  ["z",                      "with / from"],
  ["za",                     "behind / for"],
  ["zachód",                 "west",                   "m", "🧭⬅️"],
  ["zachód słońca",          "sunset",                 "m", "🌇", "weather"],
  ["zajęty",                 "busy",                   "⌛"],
  ["zamknięty",              "closed",                 "🔒"],
  ["zawód",                  "profession",             "m", "nuclear"],
  ["zawór",                  "valve",                  "m", "🚰", "nuclear"],
  ["zawsze",                 "always"],
  ["ząb",                    "tooth",                  "m", "🦷"],
  ["zbyt",                   "too (excessively)"],
  ["zdjęcie",                "photo",                  "n", "📷"],
  ["zdrowie",                "health",                 "n", "🍎💪"],
  ["zdrowy",                 "healthy",                "💪🍎"],
  ["zegar",                  "clock",                  "m", "🕰️"],
  ["zegarek",                "watch",                  "m", "⌚"],
  ["zero",                   "0",                      "0️⃣", "numbers"],
  ["zewnętrzny",             "external"],
  ["zielony",                "green",                  "🟢"],
  ["zima",                   "winter",                 "f", "❄️", "calendar"],
  ["zimny",                  "cold",                   "🥶"],
  ["złoty",                  "gold",                   "🥇"],
  ["zły",                    "bad / angry",            "👎😠"],
  ["zmęczenie",              "fatigue",                "n", "😴", "handover", "nuclear"],
  ["zmiana",                 "shift",                  "f", "🔄", "handover", "nuclear"],
  ["znowu",                  "again"],
  ["Zrozumiałem",            "Understood (said by a man)","🫡", "handover", "phrase"],
  ["zupa",                   "soup",                   "f", "🍲"],
  ["zwierzę",                "animal",                 "n", "🐾"],
  // — Ż —
  ["zespół",                 "team",                   "m", "👥", "sports"],
  ["żaden",                  "none"],
  ["że",                     "that"],
  ["żeby",                   "so that / in order to"],
  ["żołnierz",               "soldier",                "m", "💂"],
  ["żona",                   "wife",                   "f", "👰", "family"],
  ["żółty",                  "yellow",                 "🟡"],
  ["życie",                  "life",                   "n", "🌱"],
];
(function dedupeCommonWords(){
  const seen=new Set(), keep=[];
  for(const w of COMMON_WORDS){ const k=String(w[0]).toLowerCase(); if(seen.has(k)) continue; seen.add(k); keep.push(w); }
  COMMON_WORDS.length=0; COMMON_WORDS.push(...keep);
})();
