/* =====================================================================
   words.js — your vocabulary bank for Nuklearny Polski
   ---------------------------------------------------------------------
   THIS FILE IS YOURS TO EDIT. The app code lives in index.html and never
   needs to change when you add words here. Just keep both files together
   and upload both when you publish.

   Format:  ["polish", "english"]   (base/dictionary forms, lowercase)
   Sorted A->Z by the Polish word, with // -- X -- letter dividers.
   To add a word: find its letter, drop in a new line in order, save.
   ===================================================================== */

const COMMON_WORDS = [
  // — A —
  ["a","and / but"],
  ["albo","or"],
  ["ale","but"],
  ["ani","nor"],
  ["apteka","pharmacy"],
  ["autobus","bus"],

  // — B —
  ["babcia","grandmother"],
  ["bać się","to be afraid"],
  ["bank","bank"],
  ["bardzo","very"],
  ["bez","without"],
  ["biały","white"],
  ["biblioteka","library"],
  ["biedny","poor"],
  ["biegać","to run"],
  ["bilet","ticket"],
  ["biuro","office"],
  ["blisko","near"],
  ["bo","because"],
  ["bogaty","rich"],
  ["ból","pain"],
  ["brać","to take"],
  ["brat","brother"],
  ["brązowy","brown"],
  ["brudny","dirty"],
  ["brzuch","stomach / belly"],
  ["brzydki","ugly"],
  ["budować","to build"],
  ["burza","storm"],
  ["buty","shoes"],
  ["być","to be"],

  // — C —
  ["cały","whole"],
  ["cel","goal / aim"],
  ["cena","price"],
  ["chcieć","to want"],
  ["chleb","bread"],
  ["chłodny","cool"],
  ["chłopiec","boy"],
  ["chmura","cloud"],
  ["chociaż","although"],
  ["choć","although"],
  ["chodzić","to walk / go"],
  ["choroba","illness"],
  ["chory","sick"],
  ["chwila","moment"],
  ["ciało","body"],
  ["cichy","quiet"],
  ["ciekawy","interesting"],
  ["ciemny","dark"],
  ["cienki","thin"],
  ["ciepły","warm"],
  ["cieszyć się","to be glad"],
  ["ciężki","heavy / hard"],
  ["ciocia","aunt"],
  ["co","what"],
  ["coś","something"],
  ["córka","daughter"],
  ["cukier","sugar"],
  ["czapka","cap"],
  ["czarny","black"],
  ["czas","time"],
  ["czasem","sometimes"],
  ["czekać","to wait"],
  ["czemu","why / what for"],
  ["czerwiec","June"],
  ["czerwony","red"],
  ["często","often"],
  ["część","part"],
  ["człowiek","person / human"],
  ["czterdzieści","forty"],
  ["czternaście","fourteen"],
  ["czuć","to feel"],
  ["czwartek","Thursday"],
  ["czy","whether"],
  ["czyj","whose"],
  ["czysty","clean"],
  ["czytać","to read"],

  // — D —
  ["dać","to give"],
  ["daleko","far"],
  ["data","date"],
  ["dawać","to give"],
  ["decydować","to decide"],
  ["deszcz","rain"],
  ["dla","for"],
  ["dlaczego","why"],
  ["długi","long"],
  ["długopis","pen"],
  ["długość","length"],
  ["do","to / into"],
  ["dobry","good"],
  ["dokąd","where to"],
  ["dolny","lower"],
  ["dom","house / home"],
  ["dostać","to get / receive"],
  ["dość","enough / quite"],
  ["drewno","wood"],
  ["droga","road / way"],
  ["drogi","expensive / dear"],
  ["drugi","second"],
  ["drzewo","tree"],
  ["drzwi","door"],
  ["duży","big"],
  ["dwadzieścia","twenty"],
  ["dwanaście","twelve"],
  ["dworzec","station (rail/bus)"],
  ["dyrektor","director"],
  ["dziadek","grandfather"],
  ["działać","to work / operate"],
  ["dzieci","children"],
  ["dziecko","child"],
  ["dzień","day"],
  ["dziewczyna","girl"],
  ["dziewięćdziesiąt","ninety"],
  ["dziewiętnaście","nineteen"],
  ["dziękować","to thank"],
  ["dzwonić","to call / ring"],

  // — E —
  ["edukacja","education"],
  ["ekspert","expert"],
  ["energia","energy"],

  // — F —
  ["filiżanka","cup"],
  ["film","film"],
  ["fioletowy","purple"],
  ["firma","company"],

  // — G —
  ["gazeta","newspaper"],
  ["gdy","when"],
  ["gdzie","where"],
  ["głośny","loud"],
  ["głowa","head"],
  ["główny","main"],
  ["gorący","hot"],
  ["gorzki","bitter"],
  ["gospodarka","economy"],
  ["gość","guest"],
  ["gotować","to cook"],
  ["gotowy","ready"],
  ["góra","mountain"],
  ["górny","upper"],
  ["grać","to play"],
  ["granica","border"],
  ["gruby","thick / fat"],
  ["grudzień","December"],
  ["gwiazda","star"],

  // — H —
  ["historia","history / story"],
  ["hotel","hotel"],

  // — I —
  ["i","and"],
  ["ich","their"],
  ["ile","how much / how many"],
  ["ilość","quantity"],
  ["inny","other"],
  ["inżynier","engineer"],
  ["iść","to go (on foot)"],

  // — J —
  ["ja","I"],
  ["jabłko","apple"],
  ["jajko","egg"],
  ["jak","how"],
  ["jaki","what kind of"],
  ["jako","as"],
  ["jakość","quality"],
  ["jasny","bright / light"],
  ["jechać","to go (by vehicle)"],
  ["jedenaście","eleven"],
  ["jego","his"],
  ["jej","her"],
  ["jesień","autumn"],
  ["jeszcze","still / yet"],
  ["jeść","to eat"],
  ["jeśli","if"],
  ["jezioro","lake"],
  ["jeździć","to travel / drive"],
  ["jeżeli","if"],
  ["język","language / tongue"],
  ["już","already"],

  // — K —
  ["kalendarz","calendar"],
  ["kamień","stone"],
  ["karta","card"],
  ["kawiarnia","café"],
  ["każdy","each / every"],
  ["kiedy","when"],
  ["kierowca","driver"],
  ["kierownik","manager"],
  ["kino","cinema"],
  ["klient","customer"],
  ["klucz","key"],
  ["kłamstwo","lie"],
  ["kobieta","woman"],
  ["kochać","to love"],
  ["kolacja","supper"],
  ["kolega","colleague / friend (m)"],
  ["koleżanka","friend (f)"],
  ["kolor","color"],
  ["komputer","computer"],
  ["koniec","end"],
  ["kontrolować","to control"],
  ["koń","horse"],
  ["kończyć","to finish"],
  ["koszt","cost"],
  ["koszula","shirt"],
  ["kościół","church"],
  ["kość","bone"],
  ["kot","cat"],
  ["kraj","country"],
  ["krew","blood"],
  ["krowa","cow"],
  ["król","king"],
  ["krótki","short"],
  ["krzesło","chair"],
  ["książka","book"],
  ["księżyc","moon"],
  ["kto","who"],
  ["ktoś","someone"],
  ["który","which"],
  ["kuchnia","kitchen"],
  ["kultura","culture"],
  ["kupić","to buy (completed)"],
  ["kupować","to buy"],
  ["kurtka","jacket"],
  ["kwaśny","sour"],
  ["kwiat","flower"],
  ["kwiecień","April"],

  // — L —
  ["lampa","lamp"],
  ["las","forest"],
  ["latać","to fly"],
  ["lato","summer"],
  ["lekarz","doctor"],
  ["lekki","light"],
  ["lew","lion"],
  ["lewy","left (side)"],
  ["leżeć","to lie down"],
  ["liczba","number"],
  ["liczyć","to count"],
  ["lipiec","July"],
  ["list","letter"],
  ["listopad","November"],
  ["liść","leaf"],
  ["litera","letter (character)"],
  ["lotnisko","airport"],
  ["lód","ice"],
  ["lub","or"],
  ["lubić","to like"],
  ["ludzie","people"],
  ["luty","February"],

  // — Ł —
  ["ładny","pretty"],
  ["łatwy","easy"],
  ["łazienka","bathroom"],
  ["łóżko","bed"],
  ["łyżka","spoon"],

  // — M —
  ["maj","May"],
  ["mały","small"],
  ["mama","mom"],
  ["martwić się","to worry"],
  ["marzec","March"],
  ["matka","mother"],
  ["mąż","husband"],
  ["metal","metal"],
  ["mężczyzna","man"],
  ["mgła","fog"],
  ["miasto","city / town"],
  ["mieć","to have"],
  ["miejsce","place"],
  ["mierzyć","to measure"],
  ["miesiąc","month"],
  ["mieszkanie","apartment"],
  ["między","between"],
  ["miękki","soft"],
  ["mięso","meat"],
  ["milion","million"],
  ["miłość","love"],
  ["miły","nice / kind"],
  ["mimo","despite"],
  ["mleko","milk"],
  ["młody","young"],
  ["moc","power"],
  ["mocny","strong"],
  ["mokry","wet"],
  ["morze","sea"],
  ["most","bridge"],
  ["może","maybe"],
  ["możliwy","possible"],
  ["móc","to be able / can"],
  ["mój","my"],
  ["mówić","to speak / say"],
  ["mózg","brain"],
  ["musieć","to have to / must"],
  ["muzeum","museum"],
  ["muzyka","music"],
  ["my","we"],
  ["myć","to wash"],
  ["mysz","mouse"],
  ["myśl","thought"],
  ["myśleć","to think"],

  // — N —
  ["na","on"],
  ["nad","above / over"],
  ["nadzieja","hope"],
  ["najpierw","first / at first"],
  ["napisać","to write (completed)"],
  ["naprawiać","to repair"],
  ["następny","next"],
  ["nasz","our"],
  ["naturalny","natural"],
  ["nauczyciel","teacher"],
  ["nauka","science / learning"],
  ["naukowiec","scientist"],
  ["nawet","even"],
  ["nic","nothing"],
  ["niebieski","blue"],
  ["niebo","sky / heaven"],
  ["niedziela","Sunday"],
  ["niedźwiedź","bear"],
  ["nieść","to carry"],
  ["nigdy","never"],
  ["nikt","nobody"],
  ["niski","low / short"],
  ["niż","than"],
  ["noc","night"],
  ["noga","leg / foot"],
  ["nos","nose"],
  ["nosić","to carry / wear"],
  ["nowy","new"],
  ["nóż","knife"],
  ["nudny","boring"],
  ["numer","number (id)"],

  // — O —
  ["o","about"],
  ["obiad","lunch / dinner"],
  ["obok","beside"],
  ["obraz","picture / painting"],
  ["od","from"],
  ["odpoczywać","to rest"],
  ["odpowiadać","to answer"],
  ["odpowiedź","answer"],
  ["ogień","fire"],
  ["ogród","garden"],
  ["ojciec","father"],
  ["okno","window"],
  ["oko","eye"],
  ["okolica","area / surroundings"],
  ["około","around / about"],
  ["ołówek","pencil"],
  ["on","he"],
  ["ona","she"],
  ["one","they (non-male)"],
  ["oni","they (men/mixed)"],
  ["ono","it"],
  ["oprócz","besides / except"],
  ["oraz","as well as"],
  ["osiemdziesiąt","eighty"],
  ["osiemnaście","eighteen"],
  ["osobno","separately"],
  ["ostatni","last"],
  ["ostry","sharp"],
  ["otwarty","open"],
  ["otwierać","to open"],
  ["owca","sheep"],
  ["owoc","fruit"],

  // — P —
  ["palec","finger"],
  ["pamiętać","to remember"],
  ["państwo","state / country"],
  ["papier","paper"],
  ["para","pair"],
  ["park","park"],
  ["patrzeć","to look"],
  ["październik","October"],
  ["pełny","full"],
  ["pewny","sure / certain"],
  ["piątek","Friday"],
  ["pić","to drink"],
  ["pielęgniarka","nurse"],
  ["pieniądze","money"],
  ["pierwszy","first"],
  ["pies","dog"],
  ["pięćdziesiąt","fifty"],
  ["piękny","beautiful"],
  ["piętnaście","fifteen"],
  ["piosenka","song"],
  ["pisać","to write"],
  ["piwo","beer"],
  ["plac","square"],
  ["plecy","back"],
  ["płacić","to pay"],
  ["płakać","to cry"],
  ["płaszcz","coat"],
  ["pływać","to swim"],
  ["po","after"],
  ["pociąg","train"],
  ["początek","beginning"],
  ["poczta","post office"],
  ["pod","under"],
  ["podczas","during"],
  ["podobny","similar"],
  ["pogoda","weather"],
  ["pokazać","to show"],
  ["pokój","room / peace"],
  ["pole","field"],
  ["policjant","police officer"],
  ["polityka","politics"],
  ["połowa","half"],
  ["południe","noon / south"],
  ["pomagać","to help"],
  ["pomarańczowy","orange"],
  ["pomóc","to help (completed)"],
  ["pomysł","idea"],
  ["poniedziałek","Monday"],
  ["ponieważ","because"],
  ["popołudnie","afternoon"],
  ["poprzedni","previous"],
  ["potem","then / afterwards"],
  ["potrzebować","to need"],
  ["powiedzieć","to say (completed)"],
  ["powietrze","air"],
  ["powód","reason"],
  ["pójść","to go (completed)"],
  ["praca","work / job"],
  ["pracować","to work"],
  ["pracownik","worker / employee"],
  ["prawda","truth"],
  ["prawdziwy","real / true"],
  ["prawo","law / right"],
  ["prawy","right (side)"],
  ["prezent","gift"],
  ["prezydent","president"],
  ["problem","problem"],
  ["prosić","to request"],
  ["prosty","simple / straight"],
  ["prowadzić","to lead / drive"],
  ["próbować","to try"],
  ["prywatny","private"],
  ["przed","before / in front of"],
  ["przemysł","industry"],
  ["przez","through / by"],
  ["przy","next to"],
  ["przyjaciel","friend"],
  ["przyjaźń","friendship"],
  ["przyjść","to come"],
  ["przykład","example"],
  ["przystanek","(bus/tram) stop"],
  ["ptak","bird"],
  ["publiczny","public"],
  ["pusty","empty"],
  ["pytać","to ask"],
  ["pytanie","question"],

  // — R —
  ["rano","morning"],
  ["raz","once / one time"],
  ["razem","together"],
  ["region","region"],
  ["religia","religion"],
  ["restauracja","restaurant"],
  ["ręka","hand / arm"],
  ["robić","to do / make"],
  ["rodzina","family"],
  ["rok","year"],
  ["roślina","plant"],
  ["rower","bicycle"],
  ["rozmawiać","to talk"],
  ["rozumieć","to understand"],
  ["równy","equal"],
  ["różny","different"],
  ["różowy","pink"],
  ["ryba","fish"],
  ["rynek","market square"],
  ["rzadko","rarely"],
  ["rząd","government"],
  ["rzecz","thing"],
  ["rzeka","river"],

  // — S —
  ["sam","alone / oneself"],
  ["samochód","car"],
  ["samolot","airplane"],
  ["sąsiad","neighbor"],
  ["sekunda","second"],
  ["ser","cheese"],
  ["serce","heart"],
  ["siebie","oneself"],
  ["siedemdziesiąt","seventy"],
  ["siedemnaście","seventeen"],
  ["siedzieć","to sit"],
  ["sierpień","August"],
  ["siła","strength / force"],
  ["siostra","sister"],
  ["skąd","where from"],
  ["sklep","shop"],
  ["skończyć","to finish (completed)"],
  ["skóra","skin"],
  ["słaby","weak"],
  ["słodki","sweet"],
  ["słony","salty"],
  ["słoń","elephant"],
  ["słońce","sun"],
  ["słowo","word"],
  ["słuchać","to listen"],
  ["słyszeć","to hear"],
  ["smutny","sad"],
  ["sobota","Saturday"],
  ["sok","juice"],
  ["sól","salt"],
  ["spać","to sleep"],
  ["specjalista","specialist"],
  ["spodnie","trousers"],
  ["sposób","way / manner"],
  ["spotkać","to meet"],
  ["spotykać","to meet (regularly)"],
  ["sprawa","matter / affair"],
  ["sprawdzać","to check"],
  ["sprawdzić","to check (completed)"],
  ["sprawiedliwość","justice"],
  ["sprzątać","to clean up"],
  ["sprzedawać","to sell"],
  ["sprzedawca","salesperson"],
  ["srebrny","silver"],
  ["stacja","station"],
  ["stać","to stand"],
  ["stary","old"],
  ["statek","ship"],
  ["stopa","foot"],
  ["stół","table"],
  ["strach","fear"],
  ["strona","side / page"],
  ["student","student"],
  ["styczeń","January"],
  ["suchy","dry"],
  ["sukienka","dress"],
  ["swój","one's own"],
  ["syn","son"],
  ["sypialnia","bedroom"],
  ["szary","gray"],
  ["szczęście","happiness / luck"],
  ["szef","boss"],
  ["szeroki","wide"],
  ["szerokość","width"],
  ["szesnaście","sixteen"],
  ["sześćdziesiąt","sixty"],
  ["szklanka","drinking glass"],
  ["szkło","glass"],
  ["szkoła","school"],
  ["szpital","hospital"],
  ["sztuczny","artificial"],
  ["sztuka","art"],
  ["szukać","to look for"],
  ["szybki","fast"],
  ["szyja","neck"],

  // — Ś —
  ["śmiać się","to laugh"],
  ["śmierć","death"],
  ["śniadanie","breakfast"],
  ["śnieg","snow"],
  ["śpiewać","to sing"],
  ["środa","Wednesday"],
  ["środek","middle / means"],
  ["świat","world"],
  ["świeży","fresh"],
  ["świnia","pig"],

  // — T —
  ["ta","this (fem.)"],
  ["taki","such"],
  ["także","also"],
  ["talerz","plate"],
  ["tam","there"],
  ["tamten","that one"],
  ["tani","cheap"],
  ["tańczyć","to dance"],
  ["tata","dad"],
  ["teatr","theater"],
  ["telefon","phone"],
  ["telewizor","television"],
  ["ten","this (masc.)"],
  ["też","also / too"],
  ["tłumaczyć","to translate / explain"],
  ["to","this / it"],
  ["torba","bag"],
  ["trawa","grass"],
  ["trudny","difficult"],
  ["trzeci","third"],
  ["trzydzieści","thirty"],
  ["trzynaście","thirteen"],
  ["tu","here"],
  ["tutaj","here"],
  ["twardy","hard"],
  ["twarz","face"],
  ["twój","your"],
  ["ty","you (singular)"],
  ["tydzień","week"],
  ["tylko","only"],

  // — U —
  ["ubranie","clothing"],
  ["ucho","ear"],
  ["uczeń","pupil"],
  ["uczyć się","to learn / study"],
  ["ulica","street"],
  ["umrzeć","to die"],
  ["uniwersytet","university"],
  ["usta","mouth"],
  ["używać","to use"],

  // — W —
  ["w","in"],
  ["waga","weight / scale"],
  ["wartość","value"],
  ["warzywo","vegetable"],
  ["wasz","your (plural)"],
  ["ważny","important"],
  ["wąski","narrow"],
  ["wczoraj","yesterday"],
  ["według","according to"],
  ["wesoły","cheerful"],
  ["wewnętrzny","internal"],
  ["wiara","faith"],
  ["wiatr","wind"],
  ["widelec","fork"],
  ["widzieć","to see"],
  ["wieczór","evening"],
  ["wiedza","knowledge"],
  ["wiedzieć","to know (a fact)"],
  ["wiek","century / age"],
  ["wielki","great / huge"],
  ["wielkość","size"],
  ["wierzyć","to believe"],
  ["wieś","village / countryside"],
  ["więc","so / therefore"],
  ["wilk","wolf"],
  ["wino","wine"],
  ["wiosna","spring"],
  ["władza","power / authority"],
  ["własny","own"],
  ["włączać","to turn on"],
  ["włosy","hair"],
  ["wojna","war"],
  ["wolność","freedom"],
  ["wolny","slow / free"],
  ["wracać","to come back"],
  ["wreszcie","finally"],
  ["wrócić","to return"],
  ["wrzesień","September"],
  ["wstać","to get up"],
  ["wszędzie","everywhere"],
  ["wszyscy","everyone"],
  ["wszystko","everything"],
  ["wśród","among"],
  ["wtedy","then / at that time"],
  ["wtorek","Tuesday"],
  ["wujek","uncle"],
  ["wy","you (plural)"],
  ["wybierać","to choose"],
  ["wybrać","to choose (completed)"],
  ["wyłączać","to turn off"],
  ["wysoki","tall / high"],
  ["wysokość","height"],
  ["wziąć","to take (completed)"],

  // — Z —
  ["z","with / from"],
  ["za","behind / for"],
  ["zacząć","to begin (completed)"],
  ["zaczynać","to begin"],
  ["zajęty","busy"],
  ["zamknięty","closed"],
  ["zamykać","to close"],
  ["zapomnieć","to forget"],
  ["zapytać","to ask (completed)"],
  ["zawód","profession"],
  ["zawsze","always"],
  ["ząb","tooth"],
  ["zbyt","too (excessively)"],
  ["zdjęcie","photo"],
  ["zdrowie","health"],
  ["zdrowy","healthy"],
  ["zegar","clock"],
  ["zegarek","watch"],
  ["zewnętrzny","external"],
  ["zielony","green"],
  ["zima","winter"],
  ["zimny","cold"],
  ["złoty","gold"],
  ["zły","bad / angry"],
  ["zmieniać","to change"],
  ["znać","to know (be familiar)"],
  ["znaleźć","to find"],
  ["znowu","again"],
  ["zostać","to stay / become"],
  ["zrobić","to do (completed)"],
  ["zupa","soup"],
  ["zwierzę","animal"],

  // — Ż —
  ["żaden","none"],
  ["że","that"],
  ["żeby","so that / in order to"],
  ["żołnierz","soldier"],
  ["żona","wife"],
  ["żółty","yellow"],
  ["życie","life"],
  ["żyć","to live"],
];
(function dedupeCommonWords(){
  const seen=new Set(), keep=[];
  for(const w of COMMON_WORDS){ const k=String(w[0]).toLowerCase(); if(seen.has(k)) continue; seen.add(k); keep.push(w); }
  COMMON_WORDS.length=0; COMMON_WORDS.push(...keep);
})();
